# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - pandoc
  jobs:
    pre_create_environment:
      - cd docs && ln -f -s ../examples/data data && cd ..
    pre_build:
      - python -m pip install -e .

# include submodule for documenting the SOFA conventions
submodules:
  include:
    - sofar/sofa_conventions

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# use pip to install dependencies
python:
  install:
    - requirements: requirements_dev.txt
