# Config file for automatic testing at travis-ci.org

dist: bionic
language: python
python:
  - 3.7
  - 3.8
  - 3.9

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
  - tox

# Deploy to PyPI
deploy:
  provider: pypi
  username: "__token__"
  password: pypi-AgEIcHlwaS5vcmcCJDAwMzcxYTJjLTA2ZDUtNDc0Yy05MzI3LTA5NDViNjg0MjRkNwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg68pAqBad0A4A25CtlLm8-ecoy9aMN3cb--kjEAkTXb4
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
