name: test congruency regularly

on:
  workflow_dispatch:
  schedule:
    - cron: '54 * * * *'  # run every Monday at 10:00 UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements_dev.txt"
      - name: run test
        run: pytest tests/test_utils.py::test__congruency
